all: VectorOperationParallel  

VectorOperationParallel: VectorOperationParallel.c 
	gcc -std=c99 VectorOperationParallel.c -o VectorOperationParallel -lpthread -lm

clean:
	rm VectorOperationParallel
